/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SelfHostRouteImport } from './routes/self-host'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated.people'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedGrowthPairingIdRouteImport } from './routes/_authenticated.growth.$pairingId'
import { Route as AuthenticatedMeetingsIdRouteImport } from './routes/_authenticated.meetings.$id'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostRoute = SelfHostRouteImport.update({
  id: '/self-host',
  path: '/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthPairingIdRoute =
  AuthenticatedGrowthPairingIdRouteImport.update({
    id: '/growth/$pairingId',
    path: '/growth/$pairingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsIdRoute = AuthenticatedMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/self-host': typeof SelfHostRoute
  '/home': typeof AuthenticatedHomeRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/growth/$pairingId': typeof AuthenticatedGrowthPairingIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/self-host': typeof SelfHostRoute
  '/home': typeof AuthenticatedHomeRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/growth/$pairingId': typeof AuthenticatedGrowthPairingIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/self-host': typeof SelfHostRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/growth/$pairingId': typeof AuthenticatedGrowthPairingIdRoute
  '/_authenticated/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/self-host'
    | '/home'
    | '/people'
    | '/settings'
    | '/templates'
    | '/growth/$pairingId'
    | '/meetings/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/self-host'
    | '/home'
    | '/people'
    | '/settings'
    | '/templates'
    | '/growth/$pairingId'
    | '/meetings/$id'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/self-host'
    | '/_authenticated/home'
    | '/_authenticated/people'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/growth/$pairingId'
    | '/_authenticated/meetings/$id'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  SelfHostRoute: typeof SelfHostRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-host': {
      id: '/self-host'
      path: '/self-host'
      fullPath: '/self-host'
      preLoaderRoute: typeof SelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/$pairingId': {
      id: '/_authenticated/growth/$pairingId'
      path: '/growth/$pairingId'
      fullPath: '/growth/$pairingId'
      preLoaderRoute: typeof AuthenticatedGrowthPairingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/$id': {
      id: '/_authenticated/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthenticatedMeetingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedGrowthPairingIdRoute: typeof AuthenticatedGrowthPairingIdRoute
  AuthenticatedMeetingsIdRoute: typeof AuthenticatedMeetingsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedGrowthPairingIdRoute: AuthenticatedGrowthPairingIdRoute,
  AuthenticatedMeetingsIdRoute: AuthenticatedMeetingsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  SelfHostRoute: SelfHostRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
